import os

# MIKROTIK
LOGIN_MIKROTIK = os.getenv('LOGIN_MIKROTIK')
PASS_MIKROTIK = os.getenv('PASSWORD_MIKROTIK')
HOST_MIKROTIK = os.getenv('HOST_MIKROTIK')
PORT_MIKROTIK = os.getenv('PORT_MIKROTIK')
ENDPOINT = os.getenv('ENDPOINT')
# TELEGRAM
TEL_KEY = os.getenv('TEL_KEY')
